### PR TITLE
More boilerplate code for proper worker instantiation and fs polyfill

### PR DESCRIPTION
**Pull request by mainnet-pat**
Will not fail when monero-ts will get updated with my pr

### CODE REVIEW

**Comment by woodser** [comment]
Should the added .wasm assets be removed, since they're copied from a source location?

**Comment by mainnet-pat** [comment]
they could be added to a git ignore, or maybe linked. they are just required to be in public when for example vercel app will be built and deployed.

**Comment by woodser** [comment]
Yeah I think we should not duplicate the files themselves in the commit.

**Comment by woodser** [comment]
Closing this, please feel free to re-open if still relevant.

**Pull request closed without merging**
